// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Entity;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(WordDbContext))]
    [Migration("20230521225029_AddDefaultValues")]
    partial class AddDefaultValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("backend.Entity.Word.WordRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2023, 5, 21, 18, 50, 29, 99, DateTimeKind.Local).AddTicks(4965));

                    b.Property<string>("EnglishWord")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Frequency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsMemorized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("T_WordRecord", (string)null);
                });

            modelBuilder.Entity("backend.Entity.Word.WordRecord", b =>
                {
                    b.OwnsOne("backend.Entity.Word.Translation", "Translation", b1 =>
                        {
                            b1.Property<long>("WordRecordId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Definition")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int>("Language")
                                .HasColumnType("int");

                            b1.HasKey("WordRecordId");

                            b1.ToTable("T_WordRecord");

                            b1.WithOwner()
                                .HasForeignKey("WordRecordId");
                        });

                    b.Navigation("Translation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
